[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec49eda1a7e2df5d1d8b91f7a9e4f142b201007d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "00bbee4475d5824403a709767181cfb38a7b7049356d673a6e03fdad35038e7a"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.aarch64-linux-gnu-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0321de6974308ef4cfd87bed907574d635813b5b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "a6635372a52daac39c7af101d3dc59e7c940123fa4eb6a80df2eb27ee0cea199"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20fca8d9ac7f78f2d0e378b1ceb462e3a2e53a10"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "be55870d4c54c8ce85cc77870bf7e29b8bf74512007d37a4a0c356dca7f2f2ac"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c11ab7f5950702afcf461969eeaf5644d3a1aff4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "ccd4531b1a0f37f0c5d5eaa11bd2dba06370f3446f53e59cc08525ee7c556767"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.aarch64-linux-musl-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93ad4747be2f887434c2d72621712a5c474df8e2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "2a36986d978914fac805ee1f95bbad901c5dc31ae297358678b8c45489ef46db"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.aarch64-linux-musl-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dc5f5308700a7baf1d0f0a1683f19f31ec04c23"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "3be26902e2500219df8eb543e1d1b66c97cd19876b1242ebdd73c8bd576fb2a7"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3906639cf7ebd38f6a7fcbed95bb6665f3d13a13"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "1f9adca4044ce73eb86efdad3a6d6da24324fbdcaa828ae5bdc0af339b243b30"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.armv7l-linux-gnueabihf-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03e646b9aa9d7d413aff378260b46a310c57449f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "eb9e7b50eb30814c1e0c39e8bc2972a7c094566bcc9e10c75c39a52a52cd8c65"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b30aef35e616d5b3cd654606c62e0ac2bae267b5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "4f92cc1977256adb5dd30573605c70c89707b02332165facfb327a5a5cc9fe4b"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10b46ec3e05feb0704b94707607e94f0801b7802"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "089eb06dbb1b15055734ef3ab81c244ab319e8d902117a4be3943085d76eb2e9"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.armv7l-linux-musleabihf-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2687200e870edabb58fe91a9e24a2cabcaed6faf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "169369bb43666cd818521b5fef7c27d48df6c6aae884cf00447e3ddac236ca02"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.armv7l-linux-musleabihf-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5c348d3c67755472db15116af020be12666037f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "b1dbd3efaafe700a1d9f37845ea867bee4325ef22cf6c4e0ebcd94f7711be964"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be2ed8f92d23f44059206b4c0ad38a28b383d66c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "48c6f9e4fdab7a6870b344da8c00ab70be9356aac0986c69cf20b9e159977cd5"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-linux-gnu-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d85baac1b28bb81b49ac54c3719a37790e548fc4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "eab2cd3a10b1c8f7bf90e662294cf315b8b78bf6c3e66ded01cd8eb953ec5b2d"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "851e5b43bd66587cd74e1d13ab0d425e1337dfef"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "30c91bc8350baea63449984a4505e8ecf2bc904f2dfade713e7440cdfc4d09c8"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "192e3737c707fd444cf15cbde01ef83fc5f8ce65"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "6cf53ddb1dd0ec8f338aceee19c2e3d68bf98874569e4ee0202bea3271ba1831"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-linux-musl-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa58746938d6690aef3f5587b40124ed40106a32"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "abe249bb33117bc2b8f9f6962c70f0198de549187ff63878acde1633b5fba6d6"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-linux-musl-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd7ec46683d6532a0a499802e38b19d15c71829c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "bf337f05cb8f197f486c08f37492260a901a6516038bf02ff2ed90f520a8307d"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aca769fc3508f844504f56bb0fd1c3bd0410c67"
libgfortran_version = "3.0.0"
os = "windows"

    [[Bonmin.download]]
    sha256 = "903b1d2fc594479548f59f23d1c3669737ee6e3b36c1af1f0b84c8c48a1d318e"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-w64-mingw32-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf74fc1c32031df092495046ac4e59005cda88f6"
libgfortran_version = "4.0.0"
os = "windows"

    [[Bonmin.download]]
    sha256 = "59792b7a90c4fa7367fb6097a4aadcc57efdfbed715b9fb112c55d16bbcf0e8d"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11989ce0754ccb720150e029f91a956d8d46ea56"
libgfortran_version = "5.0.0"
os = "windows"

    [[Bonmin.download]]
    sha256 = "b4d6362fde34d7b0cf5419bb90b23c3a2309754247f6d97e217f52a28001b85f"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e98e75bbbb65aa253b39de39ec242b3a7a89ad1a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "678270d65b46e5331c0e031d95592d84a5c98b77a912086a6278659c9f9fb8bf"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.powerpc64le-linux-gnu-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6145a6d553063f3fe71ae359da49732c9e5f467a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "5f59f771acff23dc957e9dd25be48cbfb446339c549cea1344c3ddb7af8ed13e"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.powerpc64le-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4ef5f91557f2fad6fab427382eaf46acf0489c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "f1f8ecafc8daef242698b3e875dbd5173854c15df385e9645dc00ebf74049da7"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
git-tree-sha1 = "abcbfb65aac030d0d5244d180313de8bd81b6f40"
libgfortran_version = "3.0.0"
os = "macos"

    [[Bonmin.download]]
    sha256 = "4313f8ec16f23b15dd3dbb3104ee56a6a794f19d30d03d21a486b3d115a8bb2d"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Bonmin]]
arch = "x86_64"
git-tree-sha1 = "5a84e3feeba34143a8a686a0753c1286555feda6"
libgfortran_version = "4.0.0"
os = "macos"

    [[Bonmin.download]]
    sha256 = "13adcd6f924d177a814cb23e15016bb148d65bad2db5b20af65d794f73014697"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Bonmin]]
arch = "x86_64"
git-tree-sha1 = "36beec356d232f6fca649e490923d844e3248052"
libgfortran_version = "5.0.0"
os = "macos"

    [[Bonmin.download]]
    sha256 = "9ef00cca7c7f32e1c38cb15dd6a643383493f12585a7140cfbbf7b878cda969a"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5975135b51793912beda23625e0fe615a55aaad"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "32bb060eec634d080b868c5f3ba6caa2a4ac4029557e61d7b4ebb71450d39596"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-linux-gnu-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffb2b8739fe784146783bbb1008236ce6ebf9ec3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "401bc5112b3fb8119c04daa7c5b9624350211d839eadd39f50924c3994b5f393"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b757bb99735b4c086a34191abc0e942c76a1f1c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "153f20033eb0039ddbf44af08658bac25deb698f4f275087c27810624aa41545"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bb47fb2ac0d4703eef249150f29a59ee6497da6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "8f86cc730b415c029518ffae7284c84ff89dcd7a48c5411f6f48e34d9be11292"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-linux-musl-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e477ed31a85bd51652df88e8789cfd13573b8a93"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "3f1b43039517620d5b429050e3b197199cd536e18c736dc657b6b23465777168"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-linux-musl-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15dbedd5332a1a0fbfe48c4368243cf223de55fc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Bonmin.download]]
    sha256 = "8c9adf10f7057dee15349285b0827198fed204a33cc781cf8b3aefdd87c574ef"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b33ecdae0ea05c9b94f35532518493111671aa8e"
libgfortran_version = "3.0.0"
os = "windows"

    [[Bonmin.download]]
    sha256 = "9a055c88c558700c6fc2f4ffeb3a7d91e6039b0e74bb1ce35ba22ac266752345"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-w64-mingw32-libgfortran3-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e245ca4ff551f4bf83a1de83a1974c35fd8c99f"
libgfortran_version = "4.0.0"
os = "windows"

    [[Bonmin.download]]
    sha256 = "9b90c289339a546b96428cabe76aef7e1b4d53aa001984c0b479119eb5609d94"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f0df2834ccec72d73edbcf34f2b21db0419901a"
libgfortran_version = "5.0.0"
os = "windows"

    [[Bonmin.download]]
    sha256 = "bfd1cc68b3bd90a74b01ca7c654fc2f1401489c9953ffd838a0da88096e78d09"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v1.8.8+1/Bonmin.v1.8.8.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
