[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aeb91fae7f3b1db6a51b16410a3c529ed7430644"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "cadfa5b4ae62bda8922d20c5fbac878e104ce07f49e7bbc174a27ad7a60a665a"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.aarch64-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a911bb5d636af24a57d0d82fd6b42d09a6bfe87f"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "5bf48faae04c271c9445d73c9a6785a3657adac1f19bae458dd78ec8e2b3743b"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.aarch64-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b3c03f4f1f3658f89831dfb0d75031c9faea49a"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "29d35f7157e89819e643156293557cbf2108aa659f5850ccaefea7b02540232a"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57bddaae1b9ba16a3d499c119b59e6f25cdd3122"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "b7a30df0fd06939206a057efbb3959179f270ed015c4048f612ec44c56aa7473"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a2b65d366707f565911a28726642aac570ee89f"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "bc67598950fd9077dda4ca678b78200267fb3fbea68c1b5c9e41ef3905055092"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.i686-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea30262648557509904f4a7ec9bb7f7c2bc77b80"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "d0f0757926cdefd9d4b5b604833d1a17f93b9fdd8c194d363cc060eed7e30341"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.i686-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b6fea2146036b190f4a4c9b0a20beb2f9ccdd26"
os = "windows"

    [[Bonmin.download]]
    sha256 = "3a815a89e0ecc18aba4395d98c32187a6c2ccba4509675f5836af7947d66663c"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.i686-w64-mingw32-cxx11.tar.gz"
[[Bonmin]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0717b50f39eeafed6183e60b5fedc269b484417c"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "e9a05cf1c548bc53a55299778ede6f72aaa734e437fff070444ee077b74d0261"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
git-tree-sha1 = "b8f93f335ebff9b1873c4054f33b3ce90bf45325"
os = "macos"

    [[Bonmin.download]]
    sha256 = "e024e0d2d08d4e24b02639ba413f03ca71bafbbd09954172fbad462298f27bb3"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.x86_64-apple-darwin.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94a7b3bf486db53c0c515aa6d10406234ce92158"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "cb5ae876f6ac3d0bd0f159195f95706894f97d6928c33bc7b096a0529402dbec"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.x86_64-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30900bb720ac471c0b00ce11410690384971b80b"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "33379c10d58a547d3225110e05b73284c910897e6c38dab2c928709f012836aa"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.x86_64-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "175a586efb20cb3c95eaa7aa71c61ea8416655d5"
os = "windows"

    [[Bonmin.download]]
    sha256 = "fd6d0cc17dd94db0200b0e81eb3d3f8d3e2c5595e54efb08938f9a19f2135b1b"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.800+0/Bonmin.v100.800.800.x86_64-w64-mingw32-cxx11.tar.gz"
