[[Bonmin]]
arch = "aarch64"
git-tree-sha1 = "d512f6e81009a9204b04302411013340f659e3e1"
os = "macos"

    [[Bonmin.download]]
    sha256 = "73c588d16dcdbc8bba852aa2b22c09d68c5ba434a5de62602d20d932fccb1e21"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.aarch64-apple-darwin.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d566106b89bc044822851c208f54bbad054dc4b1"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "a64e36b7e1dbffedf6424bd915351818aa958635e6956378978b637b9c2cca92"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.aarch64-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5a1ade332a64fb622ce7fc535c7e76702e1b863"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "0897a69980ab7f6ec4d4eb0d33acfcde844d99fe2d92e14c11efa93b6851f551"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.aarch64-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db75883858db2057348750495a705a1ada07c710"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "db275d8106522ff5db32bbfa407cf062bc36e41715c82b27eb28f0f0bed1ef53"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c9c62bb3a9acf7512f059d05ebea78e35d1502a"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "4a67a7a9888050d24504b795e42dfabf6af1a6d8e90059a2d6aea6344bf2c4d4"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22c4f791a03d8371682b843117fc787f5f098a28"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "241e8703272f4a6154f3f91b82f4a62946aa00c829cffa450f41f1da77accc0b"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "777ecfbf5388dc4743f1fe723e01527e755c6ede"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "5d09a1aa45a3a4383c44328f243b28526008ec446955cda71e3b48db218dfbc6"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c49446158ac345c6275ed8d0aed4346463262986"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "00edbbd4ef6067e4d8a5753fd03bf86953ac81295e7c495e3ef297759c967f74"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.i686-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2da6537d443bb02115179e8115294d367e4cbf4a"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "bd660ae8b87d1c27d59396ea32b124caf6b30e69fbf8f4a9c4737a02196c5c2b"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.i686-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b36106eda5336c09f76bdec2c1b7e94286b5293"
os = "windows"

    [[Bonmin.download]]
    sha256 = "adf81c8e70163085be0428f3b55b8951bbcd3030e1520d95a11a83311e1c3e3e"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.i686-w64-mingw32-cxx11.tar.gz"
[[Bonmin]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d13dc4ebc50c08e16b2f50dc36cfb8100c272e3"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "1d6ecb0f7aa737d47c0d2e67d6fe2f1557a759338ae94190d5e27bf4b4059c8b"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
git-tree-sha1 = "de28cd947cd0a7420c26093ae65dab7f02ca5ec4"
os = "macos"

    [[Bonmin.download]]
    sha256 = "8a2357736249fc7f8e5de7c19a51c2d7d34aa744f13d274fd403a1126ee4d6d4"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.x86_64-apple-darwin.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0696242e66c4cb46550cc6198c666c41bd451db"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "c1f12da12f8e60356398d5b5d49206c62e29c02078cf263318cff653afd09b7e"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.x86_64-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a206a29fe1e2b65a69557bcaf6a435bf7015061"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "3cdd671f08e049f88bc14b41311219ebe5fe03862fa02ea69b390e92493e2a6c"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.x86_64-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf9f599eee4eddcb3ee1aa03e4edd42afd1d930b"
os = "windows"

    [[Bonmin.download]]
    sha256 = "53a05e2194c6df279222b8f3d47fb482b51ad0995e34ef3824ef7cf1d48c5fef"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.902+0/Bonmin.v100.800.902.x86_64-w64-mingw32-cxx11.tar.gz"
