[[Bonmin]]
arch = "aarch64"
git-tree-sha1 = "1008c47ff06713010810696803f95d5b88015296"
os = "macos"

    [[Bonmin.download]]
    sha256 = "dc17895a410373b58f5d9813032894a8b3ded9c5bed02ffbb34dce142ba14537"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.aarch64-apple-darwin.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5f8fe6e9ea03b5147efe9c26fca52b161fb4e21"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "7a21c2b977fd9b61143192361eca7f7224e0bf690b1c1cb4b99ef05200130cb1"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.aarch64-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0013b19647df07e433371ee36baf23563c6ede7a"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "9ba534f083f2a7c1a5f8f0e7e6fa21d2de858c35110dca1acac7d15731cac736"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.aarch64-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9138639025358dd0937e01a2c9ff004ceac93f34"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "ac51eb46d99e747c7877e24af9d1b93a3208d70b336a3197db0ab15530a8e099"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42db7a265ca99271e08879e68a8dea0f309af630"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "a3df34966a0310d4d12e2a603ec67995241766f1f7e15b0c68e07376a9b6b1df"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e502cb209322cc5ce1a5f19230e44a3dda1b63b0"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "570307de91ac051ce7d0d9ec01ef03c12bc4279c523a30b2d979b22453ca0301"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db325f33dbba8f3868e244ee0cd9020e544a2ee3"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "d6dd0a0a3514c809ff7afad2dbce444235c5cdf03dbd5716672359dc024745d1"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe94c0acde82744eaacbd824aa70e6f63d3732de"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "7ca28ade9278b370a542c0d16fd527f90fbf79566d0d40c53786c535a1c37a32"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.i686-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "519ec48316d5de8012013f7c332eb4543dca730c"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "b7e996ec8b7d5e04f6a028927b7cc2833186cbfbe07b96d3e587113129de183e"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.i686-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "371ca98316e44be7e533f74d28811030b29febd8"
os = "windows"

    [[Bonmin.download]]
    sha256 = "0a9059a4550ee394213302058b2c4fe733052a4f33f28adc7046d5ae14a72335"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.i686-w64-mingw32-cxx11.tar.gz"
[[Bonmin]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8253ecf8c7d33148b3729949394a00efad034a9"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "0d0b0bd6e1749e618976cad06c903b75d64eaa666f96477256e078217a093239"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
git-tree-sha1 = "d71b8536418ffa33bbc5840c35ac6d3283debe05"
os = "macos"

    [[Bonmin.download]]
    sha256 = "5a27c896159a635d8b97067f8ac3fc8670f4d3ed5bda81844794d2196ac27b65"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.x86_64-apple-darwin.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e220d049fa0adb6147b25180d2c228c69a65cce"
libc = "glibc"
os = "linux"

    [[Bonmin.download]]
    sha256 = "050dd9a25c2a69608c565d3687749729ffaccafb4c36e3ee7c1589db09288501"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.x86_64-linux-gnu-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "930a49d86ac5eab7df8d81c2befd968e2edf303c"
libc = "musl"
os = "linux"

    [[Bonmin.download]]
    sha256 = "9b54b80a75267768099679c9af5c1a226adcf6443f5bb3b446109f0f5686292e"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.x86_64-linux-musl-cxx11.tar.gz"
[[Bonmin]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f15b88ae0e5a58b02a983198530e1240bd60560e"
os = "windows"

    [[Bonmin.download]]
    sha256 = "65b9644eb0baa711f686fdd279c49ba2dc135850140216b47c3e83e4634e68f3"
    url = "https://github.com/JuliaBinaryWrappers/Bonmin_jll.jl/releases/download/Bonmin-v100.800.901+0/Bonmin.v100.800.901.x86_64-w64-mingw32-cxx11.tar.gz"
