# Autogenerated wrapper script for Bonmin_jll for i686-w64-mingw32-libgfortran5-cxx11
export amplexe, libbonmin

using Cbc_jll
using CompilerSupportLibraries_jll
using Ipopt_jll
JLLWrappers.@generate_wrapper_header("Bonmin")
JLLWrappers.@declare_executable_product(amplexe)
JLLWrappers.@declare_library_product(libbonmin, "libbonmin-4.dll")
function __init__()
    JLLWrappers.@generate_init_header(Cbc_jll, CompilerSupportLibraries_jll, Ipopt_jll)
    JLLWrappers.@init_executable_product(
        amplexe,
        "bin\\bonmin.exe",
    )

    JLLWrappers.@init_library_product(
        libbonmin,
        "bin\\libbonmin-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
