# Autogenerated wrapper script for Bonmin_jll for x86_64-apple-darwin
export amplexe, libbonmin, libbonminampl

using ASL_jll
using Cbc_jll
using Cgl_jll
using Clp_jll
using Osi_jll
using CoinUtils_jll
using Ipopt_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Bonmin")
JLLWrappers.@declare_executable_product(amplexe)
JLLWrappers.@declare_library_product(libbonmin, "@rpath/libbonmin.4.dylib")
JLLWrappers.@declare_library_product(libbonminampl, "@rpath/libbonminampl.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header(ASL_jll, Cbc_jll, Cgl_jll, Clp_jll, Osi_jll, CoinUtils_jll, Ipopt_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/bonmin",
    )

    JLLWrappers.@init_library_product(
        libbonmin,
        "lib/libbonmin.4.8.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbonminampl,
        "lib/libbonminampl.4.8.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
