# Autogenerated wrapper script for Bonmin_jll for x86_64-w64-mingw32-cxx11
export amplexe, libbonmin, libbonminampl

using ASL_jll
using Cbc_jll
using Cgl_jll
using Clp_jll
using Osi_jll
using CoinUtils_jll
using Ipopt_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Bonmin")
JLLWrappers.@declare_executable_product(amplexe)
JLLWrappers.@declare_library_product(libbonmin, "libbonmin-4.dll")
JLLWrappers.@declare_library_product(libbonminampl, "libbonminampl-4.dll")
function __init__()
    JLLWrappers.@generate_init_header(ASL_jll, Cbc_jll, Cgl_jll, Clp_jll, Osi_jll, CoinUtils_jll, Ipopt_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        amplexe,
        "bin\\bonmin.exe",
    )

    JLLWrappers.@init_library_product(
        libbonmin,
        "bin\\libbonmin-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbonminampl,
        "bin\\libbonminampl-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
